#!/bin/sh

unamestr=`uname`
if [ "$unamestr" = 'Darwin' ]; then
   platform='osx'
elif [ "$unamestr" = 'Linux' ]; then
   platform='linux'
fi

if [ "$platform" = 'osx' ]; then
   echo '- [OS X] Assuming you already have dependencies installed...'
   pg_user=`whoami`
elif [ "$platform" = 'linux' ]; then
   apt-get -y update

   echo "- installing postgres + postgis"
   apt-get install -y postgres-xc-client
   apt-get install -y libpq-dev libgeos-c1 libgeos++-dev proj-bin mapnik-utils postgresql-9.3 postgresql-9.3-postgis-2.1 postgresql-contrib-9.3 unzip postgresql-client-9.3 postgresql-common postgresql-client-common postgresql-plpython-9.3
   apt-get install -y zip git vim htop bzip2 curl gdal-bin s3cmd

   echo "- setting up postgres permissions + database"
   chmod a+rx $HOME

   echo "- installing node"
   apt-get -y update
   apt-get install -y zip git vim htop bzip2 curl libleveldb-dev nodejs npm parallel
   ln -s /usr/bin/nodejs /usr/bin/node

   pg_user='postgres'
fi

npm install
